# Build configuration for code generation
targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/**/*.dart
        options:
          # Generate .g.dart files for Riverpod providers
          riverpod_generator:
            # Enable code generation for all providers
            enabled: true
